/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { BasicPlugin, BasicPluginInterface } from "../BasicPlugin";

const _abi = [
  {
    inputs: [],
    name: "upgrade",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600160008190555060b8806100276000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063d55ec69714602d575b600080fd5b60336047565b604051603e9190605d565b60405180910390f35b60006001905090565b6057816076565b82525050565b6000602082019050607060008301846050565b92915050565b6000811515905091905056fea26469706673582212200d91ea4eadab2909e114085b4c3e58e8a1598619d606f143e4dfffd15061952b64736f6c63430008030033";

export class BasicPlugin__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BasicPlugin> {
    return super.deploy(overrides || {}) as Promise<BasicPlugin>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): BasicPlugin {
    return super.attach(address) as BasicPlugin;
  }
  connect(signer: Signer): BasicPlugin__factory {
    return super.connect(signer) as BasicPlugin__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BasicPluginInterface {
    return new utils.Interface(_abi) as BasicPluginInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BasicPlugin {
    return new Contract(address, _abi, signerOrProvider) as BasicPlugin;
  }
}
